imports:
    - { resource: config_test.yml }

# Doctrine Configuration
doctrine:
    dbal:
        host:     "127.0.0.1"
        dbname:   "circle_test"
        user:     "circleci"
        password: "circleci"
